// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdtjhskeyzbcpxcgzbmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdGpoc2tleXpiY3B4Y2d6Ym1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDIwNDgsImV4cCI6MjA2MzMxODA0OH0.gkf3ODsioUAG5lRm5-cZ40IYUjKC68k8o3BqXNDL3so";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);